import type { PluginConfig } from './types';
import type { PluginConfigSchema } from 'napcat-types';

export const DEFAULT_CONFIG: PluginConfig = {
  openclaw: {
    token: '',
    gatewayUrl: 'ws://127.0.0.1:18789',
    cliPath: '/root/.nvm/versions/node/v22.22.0/bin/openclaw',
  },
  behavior: {
    privateChat: true,
    groupAtOnly: true,
    adminQQ: [],
    commandAdminOnly: false,
    userWhitelist: [],
    groupWhitelist: [],
    debounceMs: 2000,
    resolveReply: true,
    replyMaxDepth: 1,
    groupSessionMode: 'user',
  },
  media: {
    cacheEnabled: false,
    cachePath: '/tmp/napcat/napcat-plugin-openclaw/download',
    cacheMaxSizeMB: 2048,
    cacheTTLMinutes: 60,
  },
};

export function buildConfigSchema(): PluginConfigSchema {
  return [
    { key: '_header_openclaw', type: 'text', label: '── OpenClaw 连接 ──' },
    {
      key: 'openclaw.token',
      type: 'string',
      label: 'Token',
      description: 'OpenClaw 服务端令牌',
      default: DEFAULT_CONFIG.openclaw.token,
      placeholder: '请输入 OpenClaw Token',
    },
    {
      key: 'openclaw.gatewayUrl',
      type: 'string',
      label: '网关地址',
      description: 'OpenClaw WebSocket 网关地址',
      default: DEFAULT_CONFIG.openclaw.gatewayUrl,
    },
    {
      key: 'openclaw.cliPath',
      type: 'string',
      label: 'CLI 路径',
      description: 'openclaw 可执行文件路径',
      default: DEFAULT_CONFIG.openclaw.cliPath,
    },
    { key: '_header_behavior', type: 'text', label: '── 行为设置 ──' },
    {
      key: 'behavior.privateChat',
      type: 'boolean',
      label: '私聊启用',
      description: '是否响应私聊消息',
      default: DEFAULT_CONFIG.behavior.privateChat,
    },
    {
      key: 'behavior.groupAtOnly',
      type: 'boolean',
      label: '群聊仅 @',
      description: '群聊中是否仅响应 @ 消息',
      default: DEFAULT_CONFIG.behavior.groupAtOnly,
    },
    {
      key: 'behavior.adminQQ',
      type: 'string',
      label: '管理员 QQ',
      description: '管理员 QQ 号，多个用英文逗号分隔，留空表示不限制',
      default: '',
    },
    {
      key: 'behavior.commandAdminOnly',
      type: 'boolean',
      label: '指令仅管理员',
      description: '开启后 / 开头的指令仅管理员可使用，其他人的指令消息将被忽略',
      default: DEFAULT_CONFIG.behavior.commandAdminOnly,
    },
    {
      key: 'behavior.userWhitelist',
      type: 'string',
      label: '用户白名单',
      description: '允许使用的 QQ 号，多个用英文逗号分隔，留空表示不限制',
      default: '',
    },
    {
      key: 'behavior.groupWhitelist',
      type: 'string',
      label: '群白名单',
      description: '允许使用的群号，多个用英文逗号分隔，留空表示不限制',
      default: '',
    },
    {
      key: 'behavior.debounceMs',
      type: 'number',
      label: '防抖时间 (ms)',
      description: '连续消息的防抖间隔（毫秒）',
      default: DEFAULT_CONFIG.behavior.debounceMs,
    },
    {
      key: 'behavior.resolveReply',
      type: 'boolean',
      label: '解析引用消息',
      description: '是否解析消息中引用（回复）的原始内容',
      default: DEFAULT_CONFIG.behavior.resolveReply,
    },
    {
      key: 'behavior.replyMaxDepth',
      type: 'number',
      label: '引用解析深度',
      description: '引用消息的最大解析层数，默认 1（不递归解析引用中的引用）',
      default: DEFAULT_CONFIG.behavior.replyMaxDepth,
    },
    {
      key: 'behavior.groupSessionMode',
      type: 'select',
      label: '群会话模式',
      description: '群聊中的会话隔离方式',
      default: DEFAULT_CONFIG.behavior.groupSessionMode,
      options: [
        { label: '独立会话 (每人独立)', value: 'user' },
        { label: '共享会话 (群共享)', value: 'shared' },
      ],
    },
    { key: '_header_media', type: 'text', label: '── 多媒体缓存 ──' },
    {
      key: 'media.cacheEnabled',
      type: 'boolean',
      label: '启用缓存模式',
      description: '下载多媒体文件到本地，将本地路径传递给后端（而非 URL）',
      default: DEFAULT_CONFIG.media.cacheEnabled,
    },
    {
      key: 'media.cachePath',
      type: 'string',
      label: '缓存目录',
      description: '多媒体文件下载缓存路径',
      default: DEFAULT_CONFIG.media.cachePath,
    },
    {
      key: 'media.cacheMaxSizeMB',
      type: 'number',
      label: '缓存上限 (MB)',
      description: '缓存目录最大占用空间，每次写入前检查，超出则清理最旧文件',
      default: DEFAULT_CONFIG.media.cacheMaxSizeMB,
    },
    {
      key: 'media.cacheTTLMinutes',
      type: 'number',
      label: '缓存过期 (分钟)',
      description: '缓存文件定时清理间隔，默认 60 分钟',
      default: DEFAULT_CONFIG.media.cacheTTLMinutes,
    },
  ];
}
